# Generated by Django 5.1.7 on 2025-03-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='name',
            new_name='name_user',
        ),
    ]
